[tool.poetry]
name = "py-guider-help-bot-dev"
version = "0.1.0"
description = ""
authors = ["MaksimEvdokimov <maksorli@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
